### ISSUE TITLE
Webinterface throws exception

### ISSUE THREAD

**Issue by redflag237** [Homegear/Homegear-Docker#12]
Script engine (/var/lib/homegear/www/rpc/admin/index.php): PHP Fatal error:  Trait 'Symfony\Component\Routing\Matcher\Dumper\PhpMatcherTrait' not found in /var/lib/homegear/tmp/admin-ui/cache/prod/srcApp_KernelProdContainerUrlMatcher.php on line 10

Latest Image running in Docker. Occours in Logs when opening http://<ip>:2001/admin/- can anybody help, please?

**Comment by m-scheffler** [comment]
Hi @redflag237,

looks like a problem with the cache. Could you please shutdown the container, delete the local cache directory (eg. `rm -rf /homegear-data/lib/tmp/admin-ui/cache/*`), start the container and try again?

**Comment by redflag237** [comment]
Yes, works now, thanks for your support.
By the way, path was /var/lib/homegear/... for me.
