### ISSUE TITLE
Recent changes to start.sh kills your setup, removing anything from /var/lib/homegear

### ISSUE THREAD

**Issue by m0wlheld** [Homegear/Homegear-Docker#13]
Commit [091784e7c93b2597a976945c6fa98a93d4e9fe7a ](https://github.com/Homegear/Homegear-Docker/commit/091784e7c93b2597a976945c6fa98a93d4e9fe7a) introduced a severe bug in stable's `start.sh` file. 

Line 66 reads: `rm -Rf /var/lib/homegear/`

This effectively **clears the lib directory (incl. database files)** of an already set up instance, rendering it unusable.

**Comment by hfedcba** [comment]
Wow, thanks for reporting this! How could that happen? It's fixed and the stable image is being rebuild right now. Funnily only stable was affected...
