### ISSUE TITLE
Nightly Dockerfile points to non-existing deb Repo

### ISSUE THREAD

**Issue by goebelmeier** [Homegear/Homegear-Docker#15]
https://github.com/Homegear/Homegear-Docker/blob/594941893ca840938df35eb0ef0a639906bf5459/nightly/Dockerfile#L11

points towards `deb https://apt.homegear.eu/Debian/ buster/` which doesn't exist. Changing this to `deb https://apt.homegear.eu/debian/buster/homegear/stable/ buster main` resolves this issue.

**Comment by hfedcba** [comment]
This will be fixed once the new nigthies are online. The dependencies are built already and the nightly build process has started. So in one to two days the Docker images should be fixed as well.

**Comment by hfedcba** [comment]
Testing ans stable both work again... Stable will be updated to 0.7.50 tomorrow or on Sunday. The nightly Docker images will take a few more days.

**Comment by hfedcba** [comment]
Should be fixed.
