### ISSUE TITLE
Docker nightly Images are broken due to failing dependencies on installation

### ISSUE THREAD

**Issue by sreichholf** [Homegear/Homegear-Docker#17]
A bunch of packages is currently broken due to dependencies to an older libhomegear-core with the current nightlies

As far as i can tell these are at least the following
- ipcam
- easyled
- easyled2
- easycam
- rsl
- rs2w

I wasn't sure where to report this exactly... so I hope it's OK to do it here.

**Comment by hfedcba** [comment]
Thanks - should be fixed now.
