### ISSUE TITLE
Family modules not loaded because of undefined symbol

### ISSUE THREAD

**Issue by teissler** [Homegear/Homegear-Docker#2]
Hello,

i have just updated my container and wondered why there are no families available.

Looking into homegear-err.log i found the following messages:

> 10/18/17 16:48:02.005 Critical: Could not open module "/var/lib/homegear/modules/mod_beckhoff.so": /var/lib/homegear/modules/mod_beckhoff.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonClientE
> 10/18/17 16:48:02.005 Critical: Could not open module "/var/lib/homegear/modules/mod_enocean.so": /var/lib/homegear/modules/mod_enocean.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonClientEi
> 10/18/17 16:48:02.005 Critical: Could not open module "/var/lib/homegear/modules/mod_homematicbidcos.so": /var/lib/homegear/modules/mod_homematicbidcos.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15on
> IsAddonClientEi
> 10/18/17 16:48:02.006 Critical: Could not open module "/var/lib/homegear/modules/mod_homematicwired.so": /var/lib/homegear/modules/mod_homematicwired.so: undefined symbol: _ZN7BaseLib7Systems8ICentral15onIsAddo$ClientEi
> 10/18/17 16:48:02.006 Critical: Could not open module "/var/lib/homegear/modules/mod_insteon.so": /var/lib/homegear/modules/mod_insteon.so: undefined symbol: _ZN7BaseLib7Systems4Peer18raiseIsAddonClientEi
> 10/18/17 16:48:02.007 Critical: Could not open module "/var/lib/homegear/modules/mod_intertechno.so": /var/lib/homegear/modules/mod_intertechno.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddon$lientEi
> 10/18/17 16:48:02.009 Critical: Could not open module "/var/lib/homegear/modules/mod_ipcam.so": /var/lib/homegear/modules/mod_ipcam.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonClientEi
> 10/18/17 16:48:02.010 Critical: Could not open module "/var/lib/homegear/modules/mod_knx.so": /var/lib/homegear/modules/mod_knx.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonClientEi
> 10/18/17 16:48:02.010 Critical: Could not open module "/var/lib/homegear/modules/mod_kodi.so": /var/lib/homegear/modules/mod_kodi.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonClientEi
> 10/18/17 16:48:02.010 Critical: Could not open module "/var/lib/homegear/modules/mod_max.so": /var/lib/homegear/modules/mod_max.so: undefined symbol: _ZN7BaseLib7Systems4Peer18raiseIsAddonClientEi
> 10/18/17 16:48:02.010 Critical: Could not open module "/var/lib/homegear/modules/mod_miscellaneous.so": /var/lib/homegear/modules/mod_miscellaneous.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsA$donClientEi
> 10/18/17 16:48:02.010 Critical: Could not open module "/var/lib/homegear/modules/mod_philipshue.so": /var/lib/homegear/modules/mod_philipshue.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonCl$entEi
> 10/18/17 16:48:02.011 Critical: Could not open module "/var/lib/homegear/modules/mod_sonos.so": /var/lib/homegear/modules/mod_sonos.so: undefined symbol: _ZN7BaseLib7Systems12DeviceFamily15onIsAddonClientEi
> 10/18/17 16:48:02.011 Critical: Could not load any family modules from "/var/lib/homegear/modules/".
> 10/18/17 16:48:02.018 RPC Server (Port 2002): Error: Could not load certificate or key file: Error while reading file.
> 10/18/17 16:48:02.019 RPC Server (Port 2003): Error: Could not load certificate or key file: Error while reading file.

Kind regards

**Comment by hfedcba** [comment]
I just quickly recreated the image. Does it work now? If not, the packages are broken and I will recreate them tomorrow.

In the meantime the nightly should work.

**Comment by teissler** [comment]
Unfortunately not, neither nightly nor the repulled latest are working.

**Comment by hfedcba** [comment]
Just tested it, it should work now ;-). The problem were binary files in the lib directory which were not overwritten by the newer versions.

**Comment by teissler** [comment]
Yes, at least with latest which i have tested, this issue is definitely fixed. Thank you!
