### ISSUE TITLE
Update requested

### ISSUE THREAD

**Issue by marbon87** [Homegear/Homegear-Docker#4]
Hi,

is anybody managing thie repository? The last image in docker hub is 3 months old and new version of homegear had been released...

**Comment by hfedcba** [comment]
Hi,

up until now the images were not created automatically. I changed that now ;-). New image is online.

Cheers,

Sathya

**Comment by marbon87** [comment]
The latest image is 6 days old again and the image contains only version 0.7.12-1492. 
I would be great to have an image with latest release version and images that are taged with the version.

**Comment by hfedcba** [comment]
Hey, the stable Docker image is created automatically once every month ;-). At some point I might implement an automatic trigger. The nightly is created daily. The auto-generated tagged version would be a little difficult right now, but at some point I might implement that as well.

**Comment by marbon87** [comment]
Sorry, but there is no nightly for rpi :)

**Comment by hfedcba** [comment]
Now there is ;-)
