### ISSUE TITLE
Nightly in Docker: "Critical: Killing child process"

### ISSUE THREAD

**Issue by nicx** [Homegear/Homegear-Docker#5]
IWith the current nightly I get this error:

```
01/14/19 16:10:43.443 Critical: Killing child process.
01/14/19 16:10:43.453 Homegear was terminated. Restarting (1)...
```

This ends in a reboot loop of homegear. Any chance to get this fixed soon? Or any possibility to downgrade to another nightly?

**Comment by hfedcba** [comment]
I'm on it. It might be, the reason is, I renamed homegear-ccu2 to homegear-ccu.

**Comment by hfedcba** [comment]
It should work again (at least the amd64 nightly). The Raspberry Pi nightly is being built at the moment.
