### ISSUE TITLE
Questions about the base image

### ISSUE THREAD

**Issue by christianbur** [Homegear/Homegear-Docker#8]
In my docker-compose.yml file I use "image: homegear/homegear:latest". I just downloaded the image:

```
# docker images |grep homegear
homegear/homegear             latest               b551ea2bffd3        9 days ago          810MB
```
Although the image was rebuilt 9 days ago, it still uses debian version [9.5](https://www.debian.org/News/2018/20180714) (current is [9.9](https://www.debian.org/releases/stable/)), so the Base Image is almost a year old. If the image is built after this [Dockerfile](https://github.com/Homegear/Homegear-Docker/blob/master/stable/Dockerfile#L1), it would have to use Debian version 9.9, wouldn't it?

```
# docker exec -it homegear bash -c "cat /etc/debian_version"
9.5
```

The second question is why is ["debian:stretch"](https://github.com/Homegear/Homegear-Docker/blob/83b54e4dd8128b075c1cfb4c44987bf011efbb2c/stable/Dockerfile#L1) used as base image and not "debian:stretch-slim", with the slim variant the homegear image would be smaller.

**Comment by hfedcba** [comment]
> If the image is built after this Dockerfile, it would have to use Debian version 9.9, wouldn't it?
Yes. But the old image was cached... I now added a "docker pull". Thank you, you noticed it.

> The second question is why is "debian:stretch" used as base image and not "debian:stretch-slim", with the slim variant the homegear image would be smaller.
I didn't know the slim variant existed. I changed it now and am testing if everything is working.

Thank you for this info, too!

Cheers,

Sathya
